from: mac

scm:
  increment: true
  checkout: true
  
vm: sodamac-vm-10-66-1-4

envs:
  version: 3.0.1
  test: value

stages:
  build:
    # 向构建主机安装SODA提供的企业签名证书
    - pwd
    - ls
    - rm -rf ./bin/
    - plugin_unity3d_install -v 5.6.1f1 --username "#{unity.username}" --password "#{unity.password}"
    - plugin_unity3d -p android -r . --apkPath bin --apkName roll_a_ball.apk
    - plugin_fir --build 1.0 --bundleId com.tencent.ball --file bin/roll_a_ball.apk  --name roll_a_ball.apk --token "#{fir.token}" --type android --version 1.0
