from: mac

scm:
  increment: true
  checkout: true

envs:
  version: 3.0.1
  build: 1.0

stages:
  build:
    # 向构建主机安装SODA提供的企业签名证书
    - rm -rf ./bin/
    - plugin_unity3d_install -v 5.6.1f1 --username "#{unity.username}" --password "#{unity.password}"
    
    - plugin_unity3d -p iphone
    
    - plugin_xcode --iosName ball.ipa --iosPath bin -r . -v 8.3.3
  
    - plugin_fir --build "#{build}" --bundleId com.tencent.ball --file bin/ball.ipa  --name ball --token "#{fir.token}" --type ios --version "#{version}"
